name: BanyqArt deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo 'step build'
        npm install
        npm run build
        
  publish:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo 'step publish'
        npm -v
        
        
